# Prog Asgmt. Matrix of orthogonal projection

## Sabahat Yaqoob
## LMS ID: 362840

In [3]:
import numpy as np 


In [18]:
basis = np.random.rand(4,2) 

In [19]:
result = np.matmul(np.matmul(basis,np.linalg.inv(np.matmul(basis.T,basis))),basis.T)

In [20]:
print(f"Basis = {basis}")
print(f"Orthogonal projection matrix = {result}")


Basis = [[0.2609984  0.92139154]
 [0.8976096  0.16428976]
 [0.44415697 0.78946164]
 [0.08679187 0.60757678]]
Orthogonal projection matrix = [[ 0.47686069 -0.06292946  0.37024263  0.32927929]
 [-0.06292946  0.93664439  0.19169191 -0.13651289]
 [ 0.37024263  0.19169191  0.34979426  0.23154447]
 [ 0.32927929 -0.13651289  0.23154447  0.23670066]]
